"""Constants for detection algorithms."""

# Template detector constants
MAX_CANDIDATE_REGIONS = 10  # Limit on candidate regions to process
TEMPLATE_PADDING_PIXELS = 10  # Padding around detected regions
DEFAULT_IOU_THRESHOLD = 0.3  # IoU threshold for non-maximum suppression
TEMPLATE_MIN_SIZE = 5  # Minimum template size in pixels

# Motion tracking constants
MIN_DETECTIONS_FOR_VELOCITY = 2
MIN_DETECTIONS_FOR_ACCELERATION = 3
FRAMES_UNTIL_OCCLUDED = 3
FRAMES_UNTIL_LOST = 10
MAX_FRAMES_FOR_PREDICTION = 5
MAX_TRACK_HISTORY = 50  # Maximum number of positions to keep in track history
VELOCITY_SMOOTHING_FACTOR = 0.3  # Alpha for exponential moving average
DEFAULT_MAX_TRACKING_DISTANCE = 100.0
DEFAULT_MAX_FRAMES_WITHOUT_UPDATE = 15

# Ensemble detector constants
DEFAULT_CONSENSUS_RATIO = 0.5
DEFAULT_IOU_THRESHOLD_ENSEMBLE = 0.3
CONFIDENCE_BOOST_FACTOR = 0.1  # Boost factor for multiple detector agreement
REDUCED_CONFIDENCE_PREDICTION = 0.7  # Confidence reduction for predictions
AGREEMENT_IOU_THRESHOLD = 0.5  # IoU threshold for detector agreement
META_CONFIDENCE_BASE = 0.7  # Base confidence for meta-learner
META_CONFIDENCE_RANGE = 0.3  # Range for meta-learner confidence adjustment

# CNN detector constants
DEFAULT_CNN_INPUT_SIZE = (512, 512)
DEFAULT_BATCH_SIZE = 32
CNN_CONFIDENCE_THRESHOLD = 0.5
CNN_IMAGE_CHANNELS = 3
CNN_PROPOSAL_STRIDE = 50
CNN_MAX_PROPOSALS = 100

# Training constants
EXCELLENT_ACCURACY_THRESHOLD = 0.9
EXCELLENT_TEMPLATE_COUNT = 5
GOOD_ACCURACY_THRESHOLD = 0.8
GOOD_TEMPLATE_COUNT = 3
FAIR_ACCURACY_THRESHOLD = 0.7
MIN_TEMPLATE_RECOMMENDATION = 3
REVIEW_ACCURACY_THRESHOLD = 0.8
SLOW_TRAINING_THRESHOLD = 300  # 5 minutes in seconds
RGB_CHANNELS = 3
NOISE_LEVEL_BASE = 10
NOISE_LEVEL_VARIATION = 30
TEMPLATE_SIMILARITY_BASE = 0.85
TEMPLATE_SIMILARITY_VARIATION = 0.01

# Color profile ranges (HSV)
CHATGPT_DARK_HSV_LOWER = (0, 0, 0)
CHATGPT_DARK_HSV_UPPER = (180, 30, 50)
CHATGPT_LIGHT_HSV_LOWER = (0, 0, 200)
CHATGPT_LIGHT_HSV_UPPER = (180, 30, 255)
ATUIN_TERMINAL_HSV_LOWER = (0, 0, 0)
ATUIN_TERMINAL_HSV_UPPER = (180, 255, 30)
ATUIN_HIGHLIGHT_HSV_LOWER = (0, 0, 150)
ATUIN_HIGHLIGHT_HSV_UPPER = (180, 100, 255)

# Aspect ratio validation ranges
CHATGPT_MIN_ASPECT_RATIO = 0.5
CHATGPT_MAX_ASPECT_RATIO = 5.0
ATUIN_MIN_ASPECT_RATIO = 0.3
ATUIN_MAX_ASPECT_RATIO = 10.0
GENERIC_MIN_ASPECT_RATIO = 0.1
GENERIC_MAX_ASPECT_RATIO = 10.0

# Morphological operation kernel size
MORPHOLOGY_KERNEL_SIZE = (5, 5)

# Template detector scale and confidence constants
TEMPLATE_SCALE_TOLERANCE = 0.01  # Tolerance for scale comparison
HIGH_CONFIDENCE_THRESHOLD = 0.9  # High confidence threshold for analysis
LOW_CONFIDENCE_THRESHOLD = 0.6  # Low confidence threshold for analysis
